Machine Learning 2019 - 2020 <br>
Week 1 - Workshop on Python preliminaries <br>
Lecturer: Dr George Leontidis <br>
Demonstrators: Wayne Andrew, Francesco Del Duchetto, George Onoufriou <br>

# INTRODUCTION <br>

As we discussed during the lecture this week is devoted on introducing the module and you having the chance to (re) visit some basic principles on python. It also provide you with an introduction to Anaconda and the use of notebook for writing code interactively.
There exists a set of simple examples on numpy. Please try to solve as many as you can. 
Solutions will be provided separately.


# EXERCISE

Please try to fill the gaps in the code below

In [4]:
#Import numpy as np and print the version number

#####
import numpy as np

print(np.__version__)
# print(np.version.version) # this works as well
#####

1.16.5


In [5]:
#Create a 1D array of numbers from 0 to 8

#####
np.arange(9)
#####

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
 #Create a 5×5 numpy array of all True’s
    
#####
np.full((5, 5), True, dtype=bool)
#####

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
#Extract all even numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#####
arr[arr % 2 == 0]
#####

array([0, 2, 4, 6, 8])

In [8]:
#Replace all even numbers in arr with -3

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
#####
arr[arr % 2 == 0] = -3
arr
#####

array([ 1, -3,  3, -3,  5, -3,  7, -3,  9])

In [10]:
#Convert a 1D array to a 2D array with 2 rows

#####
arr = np.arange(6) # arr([0, 1, 2, 3, 4, 5])
arr.reshape(2, -1)
#####

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
#Stack arrays a and b vertically

a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
#####
np.vstack([a, b])
#####

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
#Stack arrays a and b horizontally

a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
#####
np.hstack([a, b])
#####

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [13]:
#Get the common items between a and b

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
#####
np.intersect1d(a, b)
#####

array([2, 4])

In [20]:
#From array a remove all items present in array b
#Desired Output: array([1, 2, 3, 4])

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
#####
np.setdiff1d(a, b)
# a[~np.in1d(a, b)] # this works as well
#####

array([1, 2, 3, 4])

In [21]:
#Get the positions where elements of a and b match
#Desired Output: (array([1, 3, 5, 7], dtype=int64),)

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
#####
np.where(a == b)
#####

(array([1, 3, 5, 7], dtype=int64),)

In [22]:
#Convert the function maxx that works on two scalars, to work on two arrays.
#Hints:
#a = np.array([5, 7, 9, 8, 6, 4, 5])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
#Desired Output: array([6., 7., 9., 8., 9., 7., 5.])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#####
pair_max = np.vectorize(maxx, otypes = [float]) # get the maximum of 2 arrays
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#####



array([6., 7., 9., 8., 9., 7., 5.])

In [23]:
#How to swap two rows in a 2d numpy array?
#Swap rows 1 and 2 in the array arr
#Desired Output:
#> array([[3, 4, 5],
#>        [0, 1, 2],
#>        [6, 7, 8]])

#####
arr = np.arange(9).reshape(3,3)
arr[[1, 0, 2], :]
# arr[[0, 1]] = arr[[1, 0]]
# arr # this works as well
#####

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [36]:
#Print or show only 4 decimal places of the numpy array rand_arr
#Desired Output (something of that sort):
#> array([[0.4783, 0.2209, 0.9993],
#>        [0.3868, 0.1347, 0.2191],
#>        [0.3491, 0.2374, 0.6212],
#>        [0.8909, 0.4318, 0.4703]])

rand_arr = np.random.random((5,3))
#####
np.set_printoptions(precision = 4)
rand_arr
#####

array([[0.9931, 0.3033, 0.9408],
       [0.4919, 0.4122, 0.4239],
       [0.4188, 0.7451, 0.944 ],
       [0.7641, 0.2437, 0.1281]])

In [37]:
#Find the mean, median, standard deviation of iris's sepalwidth (1st column)
#Output of that sort:
#3.054 3.0 0.432146580071

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepalwidth = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1])
#####
mean, median, standard = np.mean(sepalwidth), np.median(sepalwidth), np.std(sepalwidth)
print(mean, median, standard)
#####

3.0540000000000003 3.0 0.4321465800705435


In [43]:
#Create a normalized form of iris's sepalwidth whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
#Output of that sort:
#[0.625  0.4167 0.5    0.4583 0.6667 0.7917 0.5833 0.5833 0.375  0.4583
# 0.7083 0.5833 0.4167 0.4167 0.8333 1.     0.7917 0.625  0.75   0.75
# 0.5833 0.7083 0.6667 0.5417 0.5833 0.4167 0.5833 0.625  0.5833 0.5
# 0.4583 0.5833 0.875  0.9167 0.4583 0.5    0.625  0.4583 0.4167 0.5833
# 0.625  0.125  0.5    0.625  0.75   0.4167 0.75   0.5    0.7083 0.5417
# 0.5    0.5    0.4583 0.125  0.3333 0.3333 0.5417 0.1667 0.375  0.2917
# 0.     0.4167 0.0833 0.375  0.375  0.4583 0.4167 0.2917 0.0833 0.2083
# 0.5    0.3333 0.2083 0.3333 0.375  0.4167 0.3333 0.4167 0.375  0.25
# 0.1667 0.1667 0.2917 0.2917 0.4167 0.5833 0.4583 0.125  0.4167 0.2083
# 0.25   0.4167 0.25   0.125  0.2917 0.4167 0.375  0.375  0.2083 0.3333
# 0.5417 0.2917 0.4167 0.375  0.4167 0.4167 0.2083 0.375  0.2083 0.6667
# 0.5    0.2917 0.4167 0.2083 0.3333 0.5    0.4167 0.75   0.25   0.0833
# 0.5    0.3333 0.3333 0.2917 0.5417 0.5    0.3333 0.4167 0.3333 0.4167
# 0.3333 0.75   0.3333 0.3333 0.25   0.4167 0.5833 0.4583 0.4167 0.4583
# 0.4583 0.4583 0.2917 0.5    0.5417 0.4167 0.2083 0.4167 0.5833 0.4167]

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepalwidth = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1])
#####
sMax, sMin = sepalwidth.max(), sepalwidth.min()

print((sepalwidth - sMin)/(sMax - sMin))
# print((sepalwidth - sMin)/sepalwidth.ptp()) # this works as well
#####

[0.625  0.4167 0.5    0.4583 0.6667 0.7917 0.5833 0.5833 0.375  0.4583
 0.7083 0.5833 0.4167 0.4167 0.8333 1.     0.7917 0.625  0.75   0.75
 0.5833 0.7083 0.6667 0.5417 0.5833 0.4167 0.5833 0.625  0.5833 0.5
 0.4583 0.5833 0.875  0.9167 0.4583 0.5    0.625  0.4583 0.4167 0.5833
 0.625  0.125  0.5    0.625  0.75   0.4167 0.75   0.5    0.7083 0.5417
 0.5    0.5    0.4583 0.125  0.3333 0.3333 0.5417 0.1667 0.375  0.2917
 0.     0.4167 0.0833 0.375  0.375  0.4583 0.4167 0.2917 0.0833 0.2083
 0.5    0.3333 0.2083 0.3333 0.375  0.4167 0.3333 0.4167 0.375  0.25
 0.1667 0.1667 0.2917 0.2917 0.4167 0.5833 0.4583 0.125  0.4167 0.2083
 0.25   0.4167 0.25   0.125  0.2917 0.4167 0.375  0.375  0.2083 0.3333
 0.5417 0.2917 0.4167 0.375  0.4167 0.4167 0.2083 0.375  0.2083 0.6667
 0.5    0.2917 0.4167 0.2083 0.3333 0.5    0.4167 0.75   0.25   0.0833
 0.5    0.3333 0.3333 0.2917 0.5417 0.5    0.3333 0.4167 0.3333 0.4167
 0.3333 0.75   0.3333 0.3333 0.25   0.4167 0.5833 0.4583 0.4167 0.4583
 0.4583 0.458